function trackers = config_tracker()
% config trackers to be evaluated

trackers = {
    struct('name', 'STARK',      'publish', 'NA') ...
    struct('name', 'SiamBAN',   'publish', 'NA') ...
    struct('name', 'SiamFC',    'publish', 'NA') ...
    struct('name', 'ATOM',      'publish', 'NA') ...
    struct('name', 'DiMP',      'publish', 'NA') ...
    struct('name', 'KeepTrack',       'publish', 'NA')...
    struct('name', 'TransT',       'publish', 'NA')...
    struct('name', 'RPT',       'publish', 'NA')...
    };
end


